# Generated by Django 4.2.4 on 2023-08-28 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 28, 8, 7, 35, 232598, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
